# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FGL_config = debug
  Test_config = debug
endif
ifeq ($(config),release)
  FGL_config = release
  Test_config = release
endif

PROJECTS := FGL Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

FGL:
ifneq (,$(FGL_config))
	@echo "==== Building FGL ($(FGL_config)) ===="
	@${MAKE} --no-print-directory -C . -f FGL.make config=$(FGL_config)
endif

Test: FGL
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C . -f Test.make config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f FGL.make clean
	@${MAKE} --no-print-directory -C . -f Test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FGL"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"